### ISSUE TITLE
[Feature request] Multiple cuts

### ISSUE THREAD

**Issue by vatterspun** [bartekmotyl/simple-video-cutter#14]
Some files have more than one section I'd like to take away from a recording.  This is especially true of very long single shots of an event or situation that's important e.g. birthday party or wedding.

I pictured the following addition but please discard the idea if it's out of scope.

1. Under "Enqueue," another option to set selection number with a < and > buttons and a number
2. Once the right button is pressed, it would advance to [2] and the existing selection would be grayed out
3. Another start and end sequence can be selected, while the first is static
4. To modify the first selection, click the left arrow button to return to [1] and make changes.
5. Once Enqueue is select, all edits would be added to the processing list

Repeat the above process for selection 3, 4, 5, etc.

Mockup:

![image](https://user-images.githubusercontent.com/1289134/74618688-d0041600-5100-11ea-82c6-efcd84f9a289.png)

**Comment by bartekmotyl** [comment]
Well, I was considering this feature already in the past, but decided no to realize it for sake of simplicity of the program. The main goal of this tool is to be simple and effective. The functionality you suggest can be easily achieved just by performing few times combination of select and enque. Of course you would need to join the extracted files in other tool, but this happens anyway for video cuts extracted from different files (or at least sometimes). 

On the other hand, I am considering implementing an option to "append" a cut to result of previous task (previous enqueue). This way user would be able to create longer clips composed of my cut scenes, even from different files.

**Comment by vatterspun** [comment]
> ... "append" a cut to result of previous task (previous enqueue)

Yeah that makes a lot of sense -- I like your idea better :)

**Comment by dontspamc** [comment]
Just came across your software, love it! Had the same request after 5 mins usage. Agree simplicity is key. You mention above "join in other tool" but I did not come across an obvious choice, do you have a recommendation? How about a sister application "simple-video-combiner" that wraps https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg in a user-friendly way?

**Comment by bartekmotyl** [comment]
@dontspamc Well, I usually use [Davinci Resolve](https://en.wikipedia.org/wiki/DaVinci_Resolve) but indeed this is pretty heavy stuff and I would also opt for something lighter. On the other hand there are multiple features that "must" be in such a tool (in order to be usable at all) like preview of joined material, transitions between sections, music tracks etc. which sound like something quite hard to implement. I am not sure that very simple "join N files" tool would be really that useful. 
Last but not least, I am currently working on another project, so I rather do not have time for yet another, even a small on. 
But of course I would appreciate any ideas (or even pull requests) that improve Simple Video Cutter to make the joining process (in other application) as easy as possible.

**Comment by bartekmotyl** [comment]
Multiple cuts feature has been implemented in version 0.20 (cuts are saved in separate video files). 
Possibility to save them as single file will be implemented in scope of #51
