### ISSUE TITLE
Set default cut range is required

### ISSUE THREAD

**Issue by riopapa** [bartekmotyl/simple-video-cutter#22]
Thanks very much for good tool.
I am using 0.15.0.0 for my video footage now.
I usually cut front part of mine using "[", but I always have to move to the end and click "]" to cut video.
Is it possible to set default values for "[" at the begining and for "]" at the end just after loading video footage?

One more thing, How about to add **auto play on/off** option on setting screen? Currently video is auto played when open, and not easy to "[" position while playing..

Very thanks in advance. :-)

**Comment by bartekmotyl** [comment]
Well, I somehow don't like the idea of setting cut range automatically to the end of the video. Bu instead, I plan the following: 

When selecting range by mouse (middle button): 
* When shift key is hold (when clicking middle button) then automatically select range from clicked position till the end of the video
* When control key is hold (when clicking middle button) then automatically select range from beginning of the video up to clicked position 

When using keys: 
* Pressing '[' with shift will select everything from current position until end of the video
* Pressing ']' with shift (?) will select everything from beginning up to current position 

Would this satisfy your needs?

Regarding autostart - indeed, option in settings dialog is missing. But actually it is already present in config.js file: 
`
"Autostart": true,
`
Unfortunately it seems there is a bug and setting this property to false does not work as expected (video can't be played any more at all). This also will be fixed in 0.16.

**Comment by bartekmotyl** [comment]
The autostart feature turned out to be more complicated. It basically works (if Autostart is set to false in config.js) but program does not work 100% correctly when started with stopped video. Selecting a given point on timeline doesn't work reliable. 
So, I decided to keep the Autostart parameter somehow hidden (do not add it to the settings window). 
Other features (autoamticaly selecting ranges) are implemented in v0.16.
