### ISSUE TITLE
Video not cutting ? 

### ISSUE THREAD

**Issue by Displayel** [bartekmotyl/simple-video-cutter#41]
So I load a video , set the part that I want to cut with Start and End and when I click Delete, the marked area just goes unmarked but the part is still there and not cut, whats the issue here ?

**Comment by bartekmotyl** [comment]
What do you mean by clicking 'Delete' ? I guess you mean the 'Clear selection' button, which simply clears the selection. 
In order to start cutting please click "Perform cut" button. And btw. - this program is not intended to modify existing file -instead, it cuts (or extracts) a selected portion into a new file. The original file remains unchanged.

**Comment by bartekmotyl** [comment]
Closing as no response and cannot reproduce.
